create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid,
  full_name text not null,
  email text not null,
  reg_no text not null,
  password text,
  password_hash text,
  role text not null default 'member' check (role in ('admin','member')),
  is_password_changed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.saved_codes (
  id bigint generated by default as identity primary key,
  owner_id bigint,
  owner_auth_id uuid,
  code_content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_name text not null,
  sender_auth_id uuid,
  message_text text not null,
  created_at timestamptz not null default now()
);

alter table public.users add column if not exists auth_user_id uuid;
alter table public.users add column if not exists password_hash text;
alter table public.users add column if not exists password text;
alter table public.users add column if not exists role text default 'member';
alter table public.users add column if not exists is_password_changed boolean default false;
alter table public.users add column if not exists created_at timestamptz default now();

alter table public.saved_codes add column if not exists owner_auth_id uuid;
alter table public.saved_codes add column if not exists owner_id bigint;
alter table public.saved_codes add column if not exists created_at timestamptz default now();
alter table public.saved_codes add column if not exists updated_at timestamptz default now();

alter table public.messages add column if not exists sender_auth_id uuid;
alter table public.messages add column if not exists created_at timestamptz default now();

update public.users set auth_user_id = gen_random_uuid() where auth_user_id is null;
update public.users set is_password_changed = false where is_password_changed is null;
update public.users set role = 'member' where role is null;

create unique index if not exists users_auth_user_id_uidx on public.users(auth_user_id);
create unique index if not exists users_email_uidx on public.users(lower(email));
create unique index if not exists users_reg_no_uidx on public.users(lower(reg_no));
create index if not exists saved_codes_owner_auth_id_idx on public.saved_codes(owner_auth_id);
create index if not exists messages_created_at_idx on public.messages(created_at);

alter table public.users enable row level security;
alter table public.saved_codes enable row level security;
alter table public.messages enable row level security;

-- The browser never receives the Supabase service-role key and does not access these tables directly.
-- All database operations go through the Render server.
revoke all on public.users from anon, authenticated;
revoke all on public.saved_codes from anon, authenticated;
revoke all on public.messages from anon, authenticated;

create or replace function public.touch_saved_code_updated_at()
returns trigger language plpgsql security invoker set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists saved_codes_touch_updated_at on public.saved_codes;
create trigger saved_codes_touch_updated_at
before update on public.saved_codes
for each row execute function public.touch_saved_code_updated_at();

-- Create the first admin only if one does not exist.
-- Login: admin@gsms.local OR ADMIN/2026/001
-- Temporary password: Admin@12345
insert into public.users (auth_user_id, full_name, email, reg_no, password, password_hash, role, is_password_changed)
select gen_random_uuid(), 'System Administrator', 'admin@gsms.local', 'ADMIN/2026/001', null,
'scrypt$16384$8$1$UCnymkm-w91Dm7UJFbfy-A$NEK0sMzl2bCZnr2bfz0B6Hi6HYfQrxrJVvOiV1v5NmiaZE3rgen6rFaGMH-XtiDyGH0eEcmjKYfuhvrH4updoA', 'admin', false
where not exists (select 1 from public.users where role = 'admin');
